remote_theme: "owasp/www--site-theme@main"

#override default star and watch buttons
code_user: mebjas
code_repo: CSRF-Protector-PHP

# core files/folders to exclude
exclude:
 - README.md

plugins:
 - jekyll-include-cache-0.2.0

